---

version: "3"

services:

    php:
      container_name: php
      build:
        context: ./docker/php
        dockerfile: Dockerfile
      image: "eburylabs/website:latest"
      ports:
        - "${APP_PORT}:80"
      volumes:
        - ${APP_PATH}:${DOCUMENT_ROOT}
      depends_on:
        - database

    database:
      image: mysql:latest
      container_name: database
      restart: always
      volumes:
        - eb_website_db:/var/lib/mysql
      ports:
        - "${DB_PORT}:3306"
      environment:
        - MYSQL_DATABASE=${DB_NAME}
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
    eb_website_db: